Іванов Кирил ФІТ 4-8 Варіант 8

In [1]:

import numpy as np
np.__version__

'2.0.2'

Створіть одновимірний масив (вектор) зі спадаючою послідовністю чисел, де кожне
наступне число менше попереднього на 2, починаючи з 30, та виведіть його значення.

In [6]:
vector = np.arange(30, 0, -2) #Створюємо вектор від 30 до 0, з кроком -2
vector

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
факторіалів натуральних чисел, починаючи з 1, та виведіть його значення.

In [12]:
import math
factorials = [math.factorial(i) for i in range(1, 10)] #Створюємо список факторіалів від 1 до 9
matrix = np.array(factorials).reshape(3, 3) #Перетворюємо список у матрицю 3x3
matrix

array([[     1,      2,      6],
       [    24,    120,    720],
       [  5040,  40320, 362880]])

Створіть масив розміром 4x4, заповніть його випадковими цілими числами від 1 до 10
та виведіть його значення.

In [13]:
matrix = np.random.randint(1, 11, size=(4, 4)) #Створюємо випадкову матрицю 4x4 з цілими числами від 1 до 10
matrix

array([[3, 7, 9, 3],
       [3, 5, 1, 8],
       [1, 8, 7, 5],
       [9, 7, 7, 4]])

Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та обчисліть суму всіх діагональних елементів.

In [14]:
matrix = np.random.rand(6, 6) #Створюємо випадкову матрицю 6x6 з дійсними числами від 0 до 1
diag_sum = np.trace(matrix) #Обчислюємо суму діагональних елементів (головної діагоналі)
diag_sum

np.float64(2.338955312384288)

Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними
числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання
та множення.

In [20]:
array1 = np.random.uniform(-10, 10, 4) #Створюємо 1 масив з випадковими дійсними числами від -10 до 10
array2 = np.random.uniform(-10, 10, 4) #Створюємо 2 масив з випадковими дійсними числами від -10 до 10
plus_result = array1 + array2 #+
minus_result = array1 - array2 #-
mnoj_result = array1 * array2 #множ
print(plus_result)
print(minus_result)
print(mnoj_result)

[-14.37591578 -15.29094935   1.06174909 -15.37934479]
[-3.37305676 -0.19421531  6.73011169  0.3364335 ]
[ 48.82236065  58.44385309 -11.04177307  59.1027647 ]


Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та
знайдіть їх добуток.

In [21]:
A = np.random.randint(1, 6, size=(4, 4)) #Створюємо 1 матрицю 4x4 з цілими числами від 1 до 5
B = np.random.randint(1, 6, size=(4, 4)) #Створюємо 2 матрицю 4x4 з цілими числами від 1 до 5
C = np.dot(A, B) #Знаходимо їх добуток
C

array([[61, 48, 52, 27],
       [40, 47, 44, 26],
       [60, 47, 51, 30],
       [51, 44, 44, 31]])

Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.

In [22]:
A = np.random.randint(1, 5, size=(2, 3))  #Створюємо 1 матрицію 2x3
B = np.random.randint(1, 5, size=(3, 3))  #Створюємо 1 матрицію 3x3
C = np.dot(A, B) #Множимо їх
C

array([[19, 36, 14],
       [11, 20,  7]])

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю.

In [27]:
matrix = np.random.randint(1, 8, size=(3, 3)) #Створюємо матрицю 3x3 з цілими числами від 1 до 7
det = np.linalg.det(matrix) #Знаходимо визначник
inv_matrix = np.linalg.inv(matrix)
inv_matrix


array([[ 5.14285714e-01, -8.00000000e-01,  7.14285714e-01],
       [-2.00000000e-01,  2.00000000e-01, -4.22942105e-17],
       [-1.71428571e-01,  6.00000000e-01, -5.71428571e-01]])

Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від -5 до 5 та транспонуйте її.

In [28]:
matrix = np.random.uniform(-5, 5, size=(5, 5)) #Створюємо матрицю 5x5 з дійсними числами від -5 до 5
trans_matrix = matrix.T #Транспонуємо її
trans_matrix

array([[-2.37910657e+00, -1.21022163e+00, -3.53188723e+00,
         4.90984986e+00,  2.72725529e+00],
       [ 4.71204237e+00,  4.42091903e-01, -4.72006266e+00,
        -4.51893408e+00, -4.47477255e+00],
       [-8.41237664e-01, -3.47335927e+00,  1.16121904e+00,
         3.27474225e+00,  4.90842242e+00],
       [ 1.57500407e+00,  3.51563772e+00, -1.83117547e+00,
         2.41748111e+00, -4.29773253e+00],
       [-3.65257624e+00,  4.68754438e-03,  1.88624141e+00,
        -2.95648956e+00,  2.12262310e+00]])

Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1 і знайдіть добуток матриці на вектор.

In [29]:
matrix = np.random.randint(1, 11, size=(3, 4)) #Створюємо матрицю 3x4 з випадковими цілими числами від 1 до 10
vector = np.random.rand(4, 1) #Створюємо вектор 4x1 з випадковими дійсними числами від 0 до 1
result = np.dot(matrix, vector) #Знаходимо добуток матриці на вектор
result

array([[18.87528099],
       [14.89896233],
       [12.20584096]])

Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.

In [33]:
matrix = np.random.rand(2, 3) #Створюємо матрицю 2x3 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(3, 1) #Створюємо вектор 3x1 з випадковими дійсними числами від 0 до 1
result = np.dot(matrix, vector) #Добуток матриці на вектор
result

array([[0.9919742],
       [0.4095554]])

Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть відношення елементів другої матриці до першої
(поелементне ділення).

In [35]:
A = np.random.randint(1, 11, size=(9, 9)) #Створюємо 1 матрицю 9x9 з випадковими цілими числами від 1 до 10
B = np.random.randint(1, 11, size=(9, 9)) #Створюємо 2 матрицю 9x9 з випадковими цілими числами від 1 до 10
ratio = B / A #Поелементне ділення B / A
ratio

array([[ 2.66666667,  2.        ,  4.        ,  8.        ,  1.        ,
         3.33333333, 10.        ,  3.        ,  0.875     ],
       [ 1.6       ,  0.66666667,  0.83333333,  0.14285714,  0.88888889,
         9.        ,  0.625     ,  2.25      ,  0.33333333],
       [ 1.        ,  1.25      ,  1.42857143,  1.2       ,  3.33333333,
         0.14285714,  0.16666667,  0.5       ,  1.28571429],
       [ 1.        ,  2.33333333,  1.        ,  1.        ,  1.125     ,
         0.57142857,  1.8       ,  5.        ,  0.6       ],
       [ 1.66666667,  1.16666667,  3.5       ,  1.        ,  1.5       ,
         0.85714286,  0.14285714,  5.        ,  0.2       ],
       [ 1.        ,  0.66666667,  1.        ,  1.25      ,  0.625     ,
         1.33333333,  5.        ,  1.4       ,  2.5       ],
       [ 1.6       ,  1.8       ,  1.42857143, 10.        ,  1.        ,
         0.4       ,  0.2       ,  0.57142857,  0.25      ],
       [ 1.66666667,  2.25      ,  0.42857143,  1.        ,  1

Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть їх добуток.

In [36]:
A = np.random.randint(1, 6, size=(9, 9)) #Створюємо 1 матрицю 9x9 з випадковими цілими числами від 1 до 5
B = np.random.randint(1, 6, size=(9, 9)) #Створюємо 2 матрицю 9x9 з випадковими цілими числами від 1 до 5
C = np.dot(A, B) #Добуток матриць
C

array([[ 72,  86,  80,  91, 103,  62,  89,  94, 102],
       [ 70,  82,  94,  87,  92,  70,  95,  99,  97],
       [ 78,  85,  84,  82,  90,  68,  90,  97, 104],
       [ 55,  83,  93,  84,  87,  73,  98,  98,  84],
       [ 68,  82,  81,  84,  96,  70,  85,  93,  93],
       [ 57, 102,  96,  87, 102,  71,  98, 112,  95],
       [ 72, 110, 103,  93,  97,  75, 114, 102, 101],
       [ 83, 111, 113, 117, 130,  91, 115, 122, 127],
       [ 76, 132, 110, 107, 118,  84, 128, 113, 107]])

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від -5 до 5 та знайдіть середнє арифметичне значення елементів матриці.

In [37]:
matrix = np.random.randint(-5, 6, size=(3, 3)) #Створюємо матрицю 3x3 з випадковими цілими числами від -5 до 5
ser_arf = np.mean(matrix) #Обчислюємо середнє арифметичне значення елементів
ser_arf

np.float64(-1.5555555555555556)

Створіть матрицю розміром 10x10, заповніть її випадковими дійсними числами в
діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем
значення елементу у кожному рядку матриці.

In [38]:
matrix = np.random.uniform(-2, 2, size=(10, 10)) #Створюємо матрицю 10x10 з випадковими дійсними числами від -2 до 2
min_indices = np.argmin(np.abs(matrix), axis=1) #Знаходимо індекси елементів з мінімальним модулем у кожному рядку
min_vector = matrix[np.arange(matrix.shape[0]), min_indices].reshape(-1, 1) #Формуємо вектор-стовпчик
min_vector

array([[-0.28100352],
       [ 0.1258842 ],
       [-0.3918982 ],
       [ 0.15852336],
       [ 0.19767644],
       [ 0.04117058],
       [ 0.27723441],
       [ 0.04912805],
       [-0.03068044],
       [-0.03476486]])

У ході виконання завдань ми ознайомилися з основними можливостями бібліотеки NumPy. Було створено різні масиви та матриці з випадковими цілими й дійсними числами, згенеровано числові послідовності та обчислено факторіали. Ми навчилися виконувати поелементні операції, матричне множення, знаходити обернені та транспоновані матриці, а також обчислювати середнє арифметичне й інші характеристики. Окрему увагу приділено вибору елементів за умовами